name: 'PR Comment'
description: 'Adds PR changes as comment'
author: 'Tanaya Sharma '

# Define your inputs here.
inputs:
  owner:
    description: "The owner of the repo"
    required: true
  repo:
    description: "The repository name"
    required: true
  pr_number:
    description: "The number of the Pull request"
    required: true
  token:
    description: "The token to use to access the gihub API"
    required: true

runs:
  using: node20
  main: dist/index.js
